#!/usr/bin/env bash
# Description: Generate README.md for folder (purpose and organization rules)
# Usage: generate-folder-readme.sh <folder_path> <purpose> <allowed_types> <naming_convention>
# Exit codes: 0=success, 1=failure

set -euo pipefail

FOLDER_PATH="${1:?Missing folder path}"
PURPOSE="${2:-To be determined from analysis}"
ALLOWED_TYPES="${3:-.md, .json, .sh, .py}"
NAMING_CONVENTION="${4:-Use consistent naming pattern}"

# Validate folder exists
if [[ ! -d "$FOLDER_PATH" ]]; then
  echo "Error: Folder not found: $FOLDER_PATH" >&2
  exit 1
fi

FOLDER_NAME=$(basename "$FOLDER_PATH")

# GitHub-reserved subtree must not get a generated README anywhere beneath it:
# GitHub renders .github/README.md in place of the repo-root README on the home
# page (precedence .github/README.md > README.md), so a stub there hijacks the
# landing page; nested stubs are repo-noise. Canonicalize LEXICALLY with
# `realpath -m -s` FIRST (-m: works on non-existent paths without touching disk;
# -s: do NOT expand symlinks, so the decision is by the path as written and a
# non-canonical .github/workflows/.. still collapses into .github), then skip if
# ANY component of the canonicalized path is exactly .github.
CANON_PATH="$(realpath -m -s "$FOLDER_PATH")"
case "/${CANON_PATH#/}/" in
  */.github/*)
    echo "Skipping GitHub-reserved subtree (a generated README would hijack the repo landing page or add repo-noise): $FOLDER_PATH" >&2
    exit 0
    ;;
esac

README_FILE="${FOLDER_PATH}/README.md"
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Get git info if available
FIRST_CREATED=""
if git log --all --format="%ai" -- "$FOLDER_PATH" 2>/dev/null | tail -1 | grep -q .; then
  FIRST_CREATED=$(git log --all --format="%ai" -- "$FOLDER_PATH" 2>/dev/null | tail -1 | cut -d' ' -f1)
fi

LAST_UPDATE=""
if git log -1 --format="%ai" -- "$FOLDER_PATH" 2>/dev/null | grep -q .; then
  LAST_UPDATE=$(git log -1 --format="%ai" -- "$FOLDER_PATH" 2>/dev/null | cut -d' ' -f1)
fi

# Generate README.md
cat > "$README_FILE" <<EOF
# ${FOLDER_NAME}

${PURPOSE}

---

## Purpose

This folder contains ${FOLDER_NAME} files organized according to project standards.

## Allowed File Types

${ALLOWED_TYPES}

## Naming Convention

${NAMING_CONVENTION}

## Organization Rules

Files in this folder should follow these rules:

1. Use appropriate file extensions
2. Follow naming conventions
3. Keep files organized and well-documented

## Standards

- Files must be valid format
- Use descriptive names
- Document purpose and usage

---

## Git Analysis

First created: ${FIRST_CREATED:-Unknown}
Last significant update: ${LAST_UPDATE:-Unknown}
Generated: ${TIMESTAMP}

---

*This README documents the organization patterns for this folder. Generated by rule-inspector.*
EOF

echo "Generated: $README_FILE" >&2
exit 0
