#!/usr/bin/env python3
"""Generate and ratchet the README's canonical status regions from repository state.

Description: One source of truth emits THREE marker-delimited canonical regions -- the
  headline-adjacent limits line, the hero disclosure region, and the status strip -- and
  re-derives them on demand to byte-compare against what is committed. No row's visible
  text is ever hand-written; every row is computed from a named predicate.

Usage: generate-hero-status.py --write [--readme <path>]   # regenerate the regions
       generate-hero-status.py --check [--readme <path>]   # the CI ratchet
       generate-hero-status.py --check --no-fold           # skip the browser assertion

Exit codes: 0 = ok, 1 = usage/IO error, 2 = one or more ratchet assertions failed

WHAT IS ASSERTED. Content (per-row and whole-region byte-compare, closed state enum,
predicate agreement in both directions) AND position (region order, headline adjacency,
above-the-fold visibility). Content-only assertions were a real gap: they refused every
edit to the limits statement while allowing it to be MOVED anywhere in the document,
which would have silently voided the adjacency an orchestrator ruling depends on.

NUMBERS ARE DERIVED, NEVER TRANSCRIBED. The disclosure region publishes the hero's
recorded duration, loop period, first-proof offset, truncation count and rendered inline
glyph height, each computed from a committed artifact at build time. The recorded duration
is additionally cross-validated against the capture's own first and last timestamps, so a
coordinated edit of this README and the evidence file together still cannot agree; the
glyph height is cross-validated against a live browser by the fold measurement it is
imported from, which fails if the published model and the measurement disagree.

WHY THREE REGIONS FROM ONE GENERATOR. The limits statement must sit ADJACENT to the
headline, and it must also sit INSIDE the byte-compared canonical content. With a single
contiguous block those are mutually exclusive: a limits row buried in the strip is not
adjacent to the headline, and a limits line written next to the headline escapes the
byte-compare and can be silently deleted by any lane editing this region. Emitting two
marker-delimited regions from one generator satisfies both -- every assertion below is
evaluated over their UNION.

FAIL-CLOSED IN ONE DIRECTION ONLY. A predicate input that is missing, unreadable,
unparseable, or not committed makes its predicate FALSE. The failure mode of a broken
predicate is therefore continued honest disclosure, never a silent pass.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

ROW_IDS = ["known-limits", "hero-recording", "hero-legibility", "hero-glyph",
           "supported-builds", "capability-check", "blackbox-tests", "release", "os"]

# The README under evaluation. Rebound by main() so a --readme copy is measured against its
# OWN hero width rather than the repository's; a predicate that silently read the checked-in
# README while checking a copy would report confident numbers about the wrong document.
README_PATH = REPO_ROOT / "README.md"

# Canonical regions, in the order they MUST appear in the document. `limits` first is not
# cosmetic: an orchestrator ruling on the first screen rests on the limits statement
# sitting adjacent to the headline, and adjacency that nothing asserts is adjacency that
# any later edit can quietly remove.
REGION_IDS = ("limits", "disclosure", "status")
STATES = {"passed", "not-yet", "partial"}

BEGIN = "<!-- BEGIN canonical-region id={rid} — generated by scripts/generate-hero-status.py; do not hand-edit -->"
END = "<!-- END canonical-region id={rid} -->"
MARKER_RE = re.compile(
    r"^<!-- claim-row id=(?P<id>[a-z-]+) state=(?P<state>[a-z-]+) "
    r"evidence=(?P<evidence>\S+) tracked=(?P<tracked>\S+) -->$"
)


def git(*args: str) -> str:
    try:
        return subprocess.run(["git", *args], cwd=REPO_ROOT, check=True,
                              capture_output=True, text=True).stdout
    except Exception:
        return ""


def is_committed(rel: str) -> bool:
    """Tracked by git AND present on disk.

    Tracked-ness is load-bearing, not pedantry: the reader's vantage point is a fresh
    clone, and an untracked file is simply absent there. A predicate that resolved true
    against an uncommitted working-tree file would flip a row to `passed` for a reader
    who can never see the evidence.
    """
    if not (REPO_ROOT / rel).exists():
        return False
    r = subprocess.run(["git", "ls-files", "--error-unmatch", "--", rel],
                       cwd=REPO_ROOT, capture_output=True, text=True)
    return r.returncode == 0


# --------------------------------------------------------------------------------------
# Derived hero facts. Every number the disclosure region publishes is COMPUTED here from a
# committed artifact, never transcribed. The caption previously carried a hand-typed
# session length that disagreed with every artifact by ~1 s and sat outside the canonical
# fence, so nothing regenerated it and nothing compared it. Deriving it here puts it under
# the same whole-region byte-compare as every other published claim.
# --------------------------------------------------------------------------------------

HERO_CAPTURE = ".github/assets/hero-capture.txt"
HERO_EVIDENCE = ".github/assets/hero-capture-evidence.json"
HERO_MANIFEST = ".github/assets/guard-hero.json"
HERO_ASSET = ".github/assets/guard-hero.svg"

CAPTURE_TS_RE = re.compile(r"^\[\s*(\d+\.\d+)\]\s")
CONSUMPTION_MARKER = "[ALLOW-SENTINEL] grant CONSUMED for task_id="


def _read(rel: str) -> str | None:
    p = REPO_ROOT / rel
    try:
        return p.read_text(encoding="utf-8") if p.is_file() else None
    except OSError:
        return None


def hero_facts() -> dict:
    """Derive every published hero number from committed artifacts.

    Returns {} when an input is missing or unparseable, and {'duration_conflict': ...}
    when the recorded duration disagrees with the capture's own timestamps. Both make the
    consuming row disclose the failure instead of publishing a number -- the fail-closed
    direction. The cross-validation is the point: a coordinated edit of the README region
    AND the evidence file still cannot agree with the capture's first and last timestamps.
    """
    cap, ev_raw, man_raw, svg = (_read(HERO_CAPTURE), _read(HERO_EVIDENCE),
                                 _read(HERO_MANIFEST), _read(HERO_ASSET))
    if not all((cap, ev_raw, man_raw, svg)):
        return {}
    try:
        evidence, manifest = json.loads(ev_raw), json.loads(man_raw)
    except Exception:
        return {}

    stamps = [float(m.group(1)) for m in
              (CAPTURE_TS_RE.match(ln) for ln in cap.splitlines()) if m]
    if len(stamps) < 2:
        return {}
    recomputed = round(stamps[-1] - stamps[0], 3)
    declared = evidence.get("raw_duration_s")
    if not isinstance(declared, (int, float)) or abs(float(declared) - recomputed) > 1e-6:
        return {"duration_conflict": (declared, recomputed)}

    durations = {float(d) for d in re.findall(r'\bdur="([\d.]+)s"', svg)}
    loop_s = max(durations) if durations else None

    lines = manifest.get("lines", [])
    by_id = {str(ln.get("id")): ln for ln in lines}
    marker_id = next((str(ln["id"]) for ln in lines
                      if str(ln.get("text", "")).startswith(CONSUMPTION_MARKER)), None)

    # When the proof line's reveal begins, read from the asset's own animation schedule.
    proof_s = None
    if marker_id and loop_s:
        for chunk in svg.split('<g data-role="line"')[1:]:
            if f'data-trace-id="{marker_id}"' not in chunk:
                continue
            km = re.search(r'attributeName="opacity"[^>]*keyTimes="([^"]+)"', chunk)
            if km:
                kt = [float(x) for x in km.group(1).split(";") if x.strip()]
                if len(kt) >= 2:
                    proof_s = round(kt[1] * loop_s, 2)
            break

    # Clipping, on the renderer's own fixed monospace grid -- both constants read from the
    # asset rather than assumed, so this stays correct if the renderer's geometry changes.
    vb = re.search(r'viewBox="0 0 (\d+(?:\.\d+)?) ', svg)
    logical_w = float(vb.group(1)) if vb else None
    adv = None
    am = re.search(r'<animate attributeName="width"[^>]*values="([^"]+)"', svg)
    if am:
        vals = [float(v) for v in am.group(1).split(";") if v.strip()]
        adv = next((b - a for a, b in zip(vals, vals[1:]) if b - a > 0), None)
    clipped: list[tuple[str, int]] = []
    if logical_w and adv:
        for t in re.finditer(r'<text data-trace-id="([^"]+)" x="([\d.]+)"', svg):
            ln = by_id.get(t.group(1))
            if not ln:
                continue
            x, n = float(t.group(2)), len(str(ln.get("text", "")))
            if x + n * adv > logical_w:
                clipped.append((t.group(1), n - max(0, int((logical_w - x) // adv))))

    if loop_s is None or proof_s is None or logical_w is None:
        return {}
    return {
        "duration_s": f"{recomputed:g}",
        "loop_s": f"{loop_s:g}",
        "ratio": f"{loop_s / recomputed:.2f}",
        "proof_s": f"{proof_s:g}",
        "proof_pct": f"{100.0 * proof_s / loop_s:.1f}",
        "logical_w": f"{logical_w:g}",
        "clipped_n": len(clipped),
        "total_n": len(lines),
        "worst_lost": max((c for _, c in clipped), default=0),
    }


MEASURE_SCRIPT = "scripts/measure-hero-fold.py"


def _fold_module():
    """Load the fold measurement as a module (its filename is not a Python identifier).

    Importing it rather than restating its constants is the point: the glyph figure this
    README publishes and the floor the fold gate measures against must be incapable of
    drifting apart. Returns None when it cannot be loaded, which fails the row closed.
    """
    import importlib.util
    p = REPO_ROOT / MEASURE_SCRIPT
    if not p.is_file():
        return None
    try:
        spec = importlib.util.spec_from_file_location("measure_hero_fold", p)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod
    except Exception:
        return None


def glyph_facts() -> dict:
    """The hero's rendered inline glyph height at each covered viewport, and its floor.

    Truncation used to be the whole of what a phone reader could not see, and it is gone --
    the panel was widened until every line fits. But the page then scales that wider panel
    DOWN to fit the column, so the limit moved from "cut off" to "too small to read", and a
    disclosure that still reported only truncation had become vacuous. This derives the
    replacement figure.

    Derived at build time from committed artifacts and NEVER transcribed: the asset's own
    viewBox, the README's own width attribute, and the model + floor imported from the fold
    measurement, which asserts that model against a real browser on every run.

    Returns {} when any input is missing, unreadable or uncommitted -- fail-closed, so the
    consuming rows disclose that they could not measure instead of publishing a pass.
    """
    mod = _fold_module()
    svg = _read(HERO_ASSET)
    if mod is None or svg is None or not is_committed(MEASURE_SCRIPT):
        return {}
    try:
        readme_text = README_PATH.read_text(encoding="utf-8")
    except OSError:
        return {}
    vb = re.search(r'viewBox="0 0 (\d+(?:\.\d+)?) ', svg)
    img_w = mod.hero_img_width(readme_text)
    if not vb or not img_w:
        return {}
    logical_w = float(vb.group(1))
    widths = sorted({w for w, _h, _s in mod.COMBOS}, reverse=True)
    per_viewport = [(w, mod.predict_glyph_px(w, img_w, logical_w)) for w in widths]
    if not per_viewport or any(g <= 0 for _w, g in per_viewport):
        return {}
    return {"floor_px": f"{mod.GLYPH_FLOOR_PX:g}",
            "per_viewport": per_viewport,
            "below_floor": [(w, g) for w, g in per_viewport if g < mod.GLYPH_FLOOR_PX],
            "n_covered": len(per_viewport)}


# --------------------------------------------------------------------------------------
# Named predicates. Each returns (state, visible_text, evidence, tracked).
# --------------------------------------------------------------------------------------

def measure_deny_rules() -> tuple[int, int, str] | None:
    """(total_deny, git_related_deny, source). None when no source is readable."""
    for cand in ("settings.json", "settings.template.json"):
        p = REPO_ROOT / cand
        if not p.is_file():
            continue
        try:
            deny = json.loads(p.read_text(encoding="utf-8")).get("permissions", {}).get("deny", [])
        except Exception:
            continue
        if not isinstance(deny, list):
            continue
        return len(deny), sum(1 for r in deny if "git" in str(r).lower()), cand
    return None


def pred_known_limits() -> tuple[str, str, str, str]:
    """Conjunction of two RE-EXECUTED measurements over committed, non-ignored inputs.

    Limb (ii) -- the permission layer carries at least one git-related deny rule -- is
    evaluated FIRST because it is cheap, safe and definitive. When it is false the
    conjunction is already false, so limb (i) (re-running the probe corpus) is NOT
    executed. That short-circuit can only hold the row AT not-yet; it can never flip it
    to passed, because `passed` additionally requires limb (i) to have been positively
    observed. Deletion of evidence is never positive evidence.
    """
    m = measure_deny_rules()
    corpus = "hooks/tests/fixtures/adversarial_corpus.json"
    corpus_committed = is_committed(corpus)

    if m is None:
        return ("not-yet",
                "**Known limits** — the permission surface could not be measured at "
                "build time, so this control is reported as unverified, not as passing.",
                "none", "spec-item-D")

    total, git_related, source = m
    limb_ii = git_related >= 1
    if not limb_ii:
        return (
            "not-yet",
            "**Known limits — this guard does not cover everything.** Wrapper- and "
            "redirection-prefixed `git` forms (`env -u VAR git …`, "
            "`2>/dev/null /usr/bin/git …`) are **not matched** by the Bash "
            "pre-execution gate's classifier: it returns a *successful-but-empty* "
            "parse, which counts as a healthy status and therefore suppresses the "
            "regex backstop meant to catch them. Nothing backs that up at the "
            f"permission layer either — **no deny rule mentions git** ({git_related} "
            f"of {total} deny entries contain the string `git`, recomputed from "
            f"`{source}`). These are **detection-layer measurements**: the forms were "
            "inspected, never executed, and no bypass was demonstrated end-to-end.",
            source, "spec-item-D",
        )
    # limb (ii) holds -- only now is limb (i) reachable, and it must be a live re-run.
    if not corpus_committed:
        return ("not-yet",
                "**Known limits** — the probe corpus is not committed, so coverage was "
                "not re-measured at build time and this control stays unverified.",
                "none", "spec-item-D")
    return ("not-yet",
            "**Known limits** — probe corpus present and the permission layer now "
            "carries git-related deny rules; re-running the corpus at build time is not "
            "yet wired, so this control stays unverified rather than claiming a pass.",
            corpus, "spec-item-D")


def pred_supported_builds() -> tuple[str, str, str, str]:
    art = "docs/reference/install-compatibility-matrix.md"
    if is_committed(art):
        return ("passed", "**Supported builds** — declared and committed.", art, "none")
    return ("not-yet",
            "**Supported builds** — not yet: none committed (spec item A).",
            "none", "spec-item-A")


def pred_capability_check() -> tuple[str, str, str, str]:
    doctor = REPO_ROOT / "scripts/doctor"
    has_strict = doctor.is_file() and "--strict" in doctor.read_text(
        encoding="utf-8", errors="replace")
    handshake = "scripts/capability-handshake.py"
    if has_strict and is_committed(handshake):
        # Structural presence only. Saying "passes on this host" would assert an
        # execution this predicate never performs.
        return ("passed",
                "**Strict capability check** — handshake committed and "
                "`scripts/doctor --strict` available (not executed here).",
                handshake, "none")
    return ("not-yet",
            "**Strict capability check** — not yet: handshake not committed "
            "(spec item A).", "none", "spec-item-A")


def pred_blackbox() -> tuple[str, str, str, str]:
    d = REPO_ROOT / "tests/blackbox"
    files = [p for p in d.glob("**/*") if p.is_file()] if d.is_dir() else []
    committed = [p for p in files if is_committed(str(p.relative_to(REPO_ROOT)))]
    if committed:
        # "passing" would assert a test run this predicate never performs.
        return ("passed",
                f"**Black-box guard tests** — {len(committed)} committed test file(s) "
                f"(presence only; not executed here).",
                "tests/blackbox", "none")
    return ("not-yet",
            "**Black-box guard tests** — not yet: none committed (spec item D).",
            "none", "spec-item-D")


def pred_release() -> tuple[str, str, str, str]:
    tags = [t for t in git("tag").splitlines() if t.strip()]
    if tags:
        return ("passed", f"**Release** — {tags[-1]}.", "none", "none")
    return ("not-yet", "**Release** — unreleased (no tags).", "none", "spec-item-B")


def pred_os() -> tuple[str, str, str, str]:
    runners: set[str] = set()
    wfs = sorted(list((REPO_ROOT / ".github/workflows").glob("*.yml"))
                 + list((REPO_ROOT / ".github/workflows").glob("*.yaml")))
    for wf in wfs:
        for m in re.finditer(r"runs-on:\s*(\S+)", wf.read_text(encoding="utf-8",
                                                               errors="replace")):
            runners.add(m.group(1).strip().strip("\"'"))
    if runners == {"ubuntu-latest"}:
        return ("partial",
                "**OS** — Ubuntu (CI) only; macOS unverified.",
                ".github/workflows", "none")
    return ("partial", f"**OS** — CI runners: {', '.join(sorted(runners)) or 'none'}.",
            ".github/workflows", "none")


def pred_hero_recording() -> tuple[str, str, str, str]:
    """The recorded session length and the replay's divergence from it (QF-8 disclosure).

    The replay's cadence is the RENDERER's, not the recording's, and the proof beat lands
    well into the loop rather than at landing. That divergence is disclosed with measured
    numbers instead of being closed by a renderer rewrite -- the recorded QF-8 tradeoff.
    """
    f = hero_facts()
    if "duration_conflict" in f:
        declared, recomputed = f["duration_conflict"]
        return ("not-yet",
                f"**Hero recording** — no session length is published: the capture evidence "
                f"records `{declared}` s but the capture's own first and last timestamps "
                f"give `{recomputed}` s, so the figure is withheld until they agree.",
                HERO_EVIDENCE, "hero-disclosure")
    if not f:
        return ("not-yet",
                "**Hero recording** — the hero artifacts could not be read or re-derived at "
                "build time, so no figure is published.", "none", "hero-disclosure")
    return ("passed",
            f"**Hero recording** — the recorded session ran **{f['duration_s']} s**; the "
            f"replay loops every **{f['loop_s']} s** ({f['ratio']}x the recording), and the "
            f"grant-consumed proof line first appears **{f['proof_s']} s** in — "
            f"{f['proof_pct']} % through the loop, not at landing.",
            HERO_EVIDENCE, "none")


def pred_hero_legibility() -> tuple[str, str, str, str]:
    """Whether a reader of the rendered hero can actually READ it, with measured numbers.

    Legibility is a CONJUNCTION and this row asserts both limbs: no line may be cut off at
    the panel's right edge, AND the panel must render at or above the readability floor.

    It previously asserted only the first limb. Widening the panel until nothing was
    truncated therefore turned the row green while the published text shrank and became
    LESS readable -- a row reporting one limb under the name of both. Reporting a criterion
    green while changing nothing a reader experiences is the outcome the glyph floor exists
    to refuse; reaching it by narrowing what the row measures reaches it anyway. So
    `passed` now requires both limbs, and the floor itself is untouched.
    """
    f, g = hero_facts(), glyph_facts()
    if not f or "duration_conflict" in f:
        return ("not-yet",
                "**Hero legibility** — the hero artifacts could not be measured at build "
                "time, so truncation is not reported.", "none", "hero-disclosure")
    if f["clipped_n"]:
        return ("partial",
                f"**Hero legibility** — **{f['clipped_n']} of {f['total_n']}** replayed "
                f"lines run past the {f['logical_w']} px panel and are cut off at its right "
                f"edge; the worst loses **{f['worst_lost']}** characters. The full, "
                f"untruncated text of every line is in the linked capture.",
                HERO_ASSET, "hero-clipping")
    if not g:
        return ("not-yet",
                f"**Hero legibility** — every replayed line fits inside the "
                f"{f['logical_w']} px panel, but the rendered glyph height could not be "
                f"derived at build time, so legibility is reported as unverified rather "
                f"than as passing.", HERO_ASSET, "hero-disclosure")
    if g["below_floor"]:
        return ("partial",
                f"**Hero legibility** — nothing is cut off: every replayed line fits inside "
                f"the {f['logical_w']} px panel. But fitting them took a panel that wide, "
                f"and the page scales it down to fit the column, so the inline text lands "
                f"below the {g['floor_px']} px readability floor at every measured "
                f"viewport. Un-truncated is not the same as readable, so this is reported "
                f"as partial, with the measured sizes below.",
                HERO_ASSET, "hero-glyph-floor")
    return ("passed",
            f"**Hero legibility** — every replayed line fits inside the {f['logical_w']} px "
            f"panel, nothing is cut off, and the inline text clears the {g['floor_px']} px "
            f"readability floor at every measured viewport.", HERO_ASSET, "none")


def pred_hero_glyph() -> tuple[str, str, str, str]:
    """The measured size the hero actually renders at — what a phone reader cannot see.

    The first screen must state with MEASURED NUMBERS what a phone reader cannot make out.
    While the hero was truncated, the truncation count carried that obligation; once the
    panel was widened the count went to zero and the obligation was left with nothing
    discharging it. This row discharges it, inside the same byte-compared canonical fence,
    derived at build time exactly as the recorded duration is.
    """
    g = glyph_facts()
    if not g:
        return ("not-yet",
                "**Hero inline size** — the replay's rendered glyph height could not be "
                "derived at build time, so no figure is published.",
                "none", "hero-disclosure")
    sizes = " and ".join(f"**{px:g} px** at a {w} px viewport"
                         for w, px in g["per_viewport"])
    if not g["below_floor"]:
        return ("passed",
                f"**Hero inline size** — the replay's text renders at {sizes}, clearing the "
                f"{g['floor_px']} px readability floor at every measured viewport.",
                MEASURE_SCRIPT, "none")
    n, total = len(g["below_floor"]), g["n_covered"]
    where = "every" if n == total else f"{n} of {total}"
    return ("partial",
            f"**Hero inline size** — the replay's text renders at {sizes}, against the "
            f"**{g['floor_px']} px** readability floor it misses at {where} measured "
            f"viewport. Below that floor the transcript is on the page but too small to "
            f"read there — on a phone it is roughly a third of readable size. Nothing is "
            f"cut off; it is scaled down. Read it at full size in the linked capture.",
            MEASURE_SCRIPT, "hero-glyph-floor")


PREDICATES = {
    "known-limits": pred_known_limits,
    "hero-recording": pred_hero_recording,
    "hero-legibility": pred_hero_legibility,
    "hero-glyph": pred_hero_glyph,
    "supported-builds": pred_supported_builds,
    "capability-check": pred_capability_check,
    "blackbox-tests": pred_blackbox,
    "release": pred_release,
    "os": pred_os,
}

# Which canonical region each row renders into.
REGION_OF = {"known-limits": "limits", "hero-recording": "disclosure",
             "hero-legibility": "disclosure", "hero-glyph": "disclosure"}
for _r in ROW_IDS:
    REGION_OF.setdefault(_r, "status")

# Regions whose rows render as prose rather than list items.
PROSE_REGIONS = {"limits", "disclosure"}


def render_rows() -> dict[str, list[tuple[str, str]]]:
    """-> {region_id: [(marker_line, visible_line), ...]} in ROW_IDS order."""
    out: dict[str, list[tuple[str, str]]] = {rid: [] for rid in REGION_IDS}
    for rid in ROW_IDS:
        state, text, evidence, tracked = PREDICATES[rid]()
        if state not in STATES:
            raise SystemExit(f"generator emitted an out-of-enum state for {rid}: {state}")
        marker = (f"<!-- claim-row id={rid} state={state} "
                  f"evidence={evidence} tracked={tracked} -->")
        visible = text if REGION_OF[rid] in PROSE_REGIONS else f"- {text}"
        out[REGION_OF[rid]].append((marker, visible))
    return out


def render_region(rid: str, rows: list[tuple[str, str]]) -> str:
    body = "\n".join(f"{m}\n{v}" for m, v in rows)
    return f"{BEGIN.format(rid=rid)}\n{body}\n{END.format(rid=rid)}"


def region_span(text: str, rid: str) -> tuple[int, int] | None:
    b, e = BEGIN.format(rid=rid), END.format(rid=rid)
    i, j = text.find(b), text.find(e)
    if i < 0 or j < 0 or j < i:
        return None
    return i, j + len(e)


def parse_committed_rows(region_text: str) -> list[tuple[str, str, dict]]:
    """-> [(marker_line, visible_line, parsed_marker_fields)] for each claim-row."""
    lines = region_text.splitlines()
    out = []
    for idx, ln in enumerate(lines):
        m = MARKER_RE.match(ln.strip())
        if m:
            visible = lines[idx + 1] if idx + 1 < len(lines) else ""
            out.append((ln.strip(), visible, m.groupdict()))
    return out


def _blocks_before(text: str, upto: int) -> list[str]:
    return [b for b in re.split(r"\n\s*\n", text[:upto]) if b.strip()]


def _is_heading(block: str) -> bool:
    first = block.strip().splitlines()[0] if block.strip() else ""
    return bool(re.match(r"#{1,6}\s", first.strip()))


def assert_region_positions(text: str) -> list[str]:
    """The limits region's POSITION, not merely its bytes.

    The byte-compare already refuses any edit to the region's CONTENT, but it was blind to
    the region being MOVED. That gap matters because an orchestrator ruling on the first
    screen rests entirely on the limits statement sitting next to the headline: relocate it
    below the status strip and every byte-level assertion still passes while the ruling's
    premise silently evaporates.
    """
    out: list[str] = []
    spans = {rid: region_span(text, rid) for rid in REGION_IDS}
    limits = spans.get("limits")
    if limits is None:
        return ["[region-position] the limits region is absent, so its position cannot be enforced"]

    for rid in REGION_IDS:
        span = spans.get(rid)
        if rid != "limits" and span and span[0] < limits[0]:
            out.append(f"[region-position] region {rid!r} precedes the limits region; the "
                       f"limits statement must come before every other canonical region")

    blocks = _blocks_before(text, limits[0])
    headline = next((i for i, b in enumerate(blocks)
                     if re.match(r"##\s", b.strip().splitlines()[0].strip())), None)
    if headline is None:
        return out + ["[region-position] no headline block precedes the limits region, so "
                      "headline adjacency cannot be established"]

    between = blocks[headline + 1:]
    if any(_is_heading(b) for b in between):
        out.append("[region-position] a heading intervenes between the headline block and "
                   "the limits region; the limits statement must qualify the headline")
    if len(between) > 1:
        out.append(f"[region-position] {len(between)} block elements separate the headline "
                   f"block from the limits region; at most one is allowed")
    return out


def assert_limits_above_fold(readme: Path) -> tuple[list[str], list[str]]:
    """-> (violations, notes). The limits statement must survive where it is measured.

    Scoped deliberately to the combinations the fold measurement itself covers; broadening
    to arbitrary widths would make the positive control unsatisfiable, which is the failure
    mode the previous cycle shipped.
    """
    script = REPO_ROOT / "scripts/measure-hero-fold.py"
    if not script.is_file():
        return ([], [f"[fold] {script.name} is absent; the fold assertion did NOT run"])
    try:
        r = subprocess.run([sys.executable, str(script), "--readme", str(readme)],
                           cwd=REPO_ROOT, capture_output=True, text=True, timeout=600)
        data = json.loads(r.stdout)
    except Exception as exc:
        return ([], [f"[fold] the fold measurement could not be executed "
                     f"({type(exc).__name__}); the limits region's fold position is "
                     f"UNVERIFIED in this environment"])
    results = data.get("results") or []
    if not results:
        return (["[fold] the fold measurement produced no combinations to assert over"], [])
    out = []
    for res in results:
        where = f"{res.get('viewport')}/{res.get('scheme')}"
        above = res.get("above_fold") or {}
        for element in ("headline", "limits"):
            if not above.get(element):
                out.append(f"[fold] the {element} is not fully above the fold at {where}")
    # The disclosure region publishes a glyph height derived from the fold script's model
    # rather than from a browser, because a status row must regenerate anywhere while that
    # measurement needs Chromium. `model_drift` is the fold script's own report that its
    # model and its live measurement disagree, and consuming it here is what makes the
    # published figure MEASURED rather than merely modelled.
    #
    # Deliberately NOT the whole returncode or the whole failures list: those also carry the
    # glyph-floor verdict, and importing that here would make the floor block this ratchet --
    # a scope change no ruling has made, arrived at as a side effect. The floor stays
    # disclosed and un-gated; only the honesty of the published number is enforced.
    for drift in data.get("model_drift") or []:
        out.append(f"[fold] {drift}")
    return (out, [f"[fold] asserted over {len(results)} combinations (local preview; the "
                  f"real page adds platform chrome above the README, so it can only sit lower)"])


def cmd_write(readme: Path) -> int:
    global README_PATH
    README_PATH = readme
    text = readme.read_text(encoding="utf-8")
    rows = render_rows()
    for rid in REGION_IDS:
        span = region_span(text, rid)
        if span is None:
            print(f"generate-hero-status: region {rid!r} markers not found in {readme}",
                  file=sys.stderr)
            return 1
        i, j = span
        text = text[:i] + render_region(rid, rows[rid]) + text[j:]
    readme.write_text(text, encoding="utf-8")
    print(f"generate-hero-status: wrote both canonical regions into {readme}")
    return 0


def cmd_check(readme: Path, check_fold: bool = True) -> int:
    """All four assertions, evaluated on EVERY run. Never short-circuits; every
    violation names the offending row id."""
    text = readme.read_text(encoding="utf-8")
    expected = render_rows()
    violations: list[str] = []

    committed_rows: list[tuple[str, str, dict]] = []
    for rid in REGION_IDS:
        span = region_span(text, rid)
        if span is None:
            violations.append(f"[region:{rid}] canonical region markers are missing")
            continue
        committed_rows += parse_committed_rows(text[span[0]:span[1]])

    seen: dict[str, int] = {}
    for _, _, f in committed_rows:
        seen[f["id"]] = seen.get(f["id"], 0) + 1

    # (a) completeness: every row id present EXACTLY once across the UNION of regions.
    for rid in ROW_IDS:
        n = seen.get(rid, 0)
        if n == 0:
            violations.append(f"[completeness] row {rid!r} is missing from the canonical regions")
        elif n > 1:
            violations.append(f"[completeness] row {rid!r} appears {n} times; expected exactly once")
    for rid in seen:
        if rid not in ROW_IDS:
            violations.append(f"[completeness] row {rid!r} is not in the closed row enum")

    # (b) enum: every state token within the closed three-value enum.
    for _, _, f in committed_rows:
        if f["state"] not in STATES:
            violations.append(
                f"[enum] row {f['id']!r} carries state={f['state']!r}, outside {sorted(STATES)}")

    # (c) predicate: state=passed IFF the named predicate holds -- bidirectional, so a
    #     stale not-yet left behind after an artifact appears also fails.
    expected_by_id = {}
    for rid_region, pairs in expected.items():
        for marker, visible in pairs:
            m = MARKER_RE.match(marker)
            assert m
            expected_by_id[m.group("id")] = (marker, visible, m.groupdict())
    for _, _, f in committed_rows:
        exp = expected_by_id.get(f["id"])
        if exp is None:
            continue
        if f["state"] != exp[2]["state"]:
            violations.append(
                f"[predicate] row {f['id']!r} claims state={f['state']!r} but its named "
                f"predicate evaluates to {exp[2]['state']!r}")

    # (d) per-row byte-compare, so every violation can name its row.
    for _, _, f in committed_rows:
        exp = expected_by_id.get(f["id"])
        if exp is None:
            continue
        pass
    for rid in ROW_IDS:
        exp = expected_by_id[rid]
        got = next((r for r in committed_rows if r[2]["id"] == rid), None)
        if got is None:
            continue
        if got[0] != exp[0]:
            violations.append(f"[byte-compare] row {rid!r}: marker line differs from regenerated")
        if got[1] != exp[1]:
            violations.append(f"[byte-compare] row {rid!r}: visible text differs from regenerated")

    # (e) WHOLE-REGION byte-compare. The per-row compare above only inspects recognized
    # marker/visible pairs, so free-standing authored prose inserted INSIDE a canonical
    # region -- an extra fabricated bullet, a second copy of a region -- was invisible to
    # it and exited 0. That was a genuine fail-open hole (codex review). Comparing the
    # entire region against render_region() leaves no unreviewed bytes inside the fence.
    for rid in REGION_IDS:
        span = region_span(text, rid)
        if span is None:
            continue
        committed_region = text[span[0]:span[1]]
        if committed_region != render_region(rid, expected[rid]):
            violations.append(
                f"[region-byte-compare] region {rid!r} does not match the regenerated "
                f"region exactly (content inside the canonical fence was added, removed "
                f"or reordered)")
        # Exactly one begin/end pair per region.
        if text.count(BEGIN.format(rid=rid)) != 1 or text.count(END.format(rid=rid)) != 1:
            violations.append(
                f"[region-byte-compare] region {rid!r} does not have exactly one "
                f"BEGIN/END marker pair")
    # A claim-row marker outside every canonical region is an unreviewed claim.
    inside = "".join(text[region_span(text, r)[0]:region_span(text, r)[1]]
                     for r in REGION_IDS if region_span(text, r))
    for ln in text.splitlines():
        if MARKER_RE.match(ln.strip()) and ln not in inside:
            violations.append(f"[region-byte-compare] claim-row marker outside any "
                              f"canonical region: {ln.strip()[:80]}")

    # (f) POSITION, not just bytes: region order and headline adjacency.
    violations += assert_region_positions(text)

    # (g) the limits statement is actually visible where the fold is measured.
    notes: list[str] = []
    if check_fold:
        fold_violations, fold_notes = assert_limits_above_fold(readme)
        violations += fold_violations
        notes += fold_notes

    for n in notes:
        print(f"generate-hero-status: NOTE: {n}")
    for v in violations:
        print(f"generate-hero-status: FAIL: {v}", file=sys.stderr)
    if violations:
        return 2
    print(f"generate-hero-status: OK  {len(ROW_IDS)} rows verified across "
          f"{len(REGION_IDS)} canonical regions (order, headline adjacency"
          f"{' and fold position' if check_fold else ''} asserted)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--readme", default=str(REPO_ROOT / "README.md"))
    ap.add_argument("--no-fold", action="store_true",
                    help="skip the above-the-fold assertion (it needs a headless browser)")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    a = ap.parse_args()
    readme = Path(a.readme)
    # Measure the document actually under evaluation, not the one in the repository.
    global README_PATH
    README_PATH = readme
    return cmd_write(readme) if a.write else cmd_check(readme, check_fold=not a.no_fold)


if __name__ == "__main__":
    sys.exit(main())
