#!/usr/bin/env python3
"""Generate and ratchet the README's canonical status regions from repository state.

Description: One source of truth emits TWO marker-delimited canonical regions -- the
  headline-adjacent limits line, and the five-row status strip -- and re-derives them on
  demand to byte-compare against what is committed. No row's visible text is ever
  hand-written; every row is computed from a named predicate.

Usage: generate-hero-status.py --write [--readme <path>]   # regenerate the regions
       generate-hero-status.py --check [--readme <path>]   # the CI ratchet

Exit codes: 0 = ok, 1 = usage/IO error, 2 = one or more ratchet assertions failed

WHY TWO REGIONS FROM ONE GENERATOR. The limits statement must sit ADJACENT to the
headline, and it must also sit INSIDE the byte-compared canonical content. With a single
contiguous block those are mutually exclusive: a limits row buried in the strip is not
adjacent to the headline, and a limits line written next to the headline escapes the
byte-compare and can be silently deleted by any lane editing this region. Emitting two
marker-delimited regions from one generator satisfies both -- every assertion below is
evaluated over their UNION.

FAIL-CLOSED IN ONE DIRECTION ONLY. A predicate input that is missing, unreadable,
unparseable, or not committed makes its predicate FALSE. The failure mode of a broken
predicate is therefore continued honest disclosure, never a silent pass.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

ROW_IDS = ["known-limits", "supported-builds", "capability-check",
           "blackbox-tests", "release", "os"]
STATES = {"passed", "not-yet", "partial"}

BEGIN = "<!-- BEGIN canonical-region id={rid} — generated by scripts/generate-hero-status.py; do not hand-edit -->"
END = "<!-- END canonical-region id={rid} -->"
MARKER_RE = re.compile(
    r"^<!-- claim-row id=(?P<id>[a-z-]+) state=(?P<state>[a-z-]+) "
    r"evidence=(?P<evidence>\S+) tracked=(?P<tracked>\S+) -->$"
)


def git(*args: str) -> str:
    try:
        return subprocess.run(["git", *args], cwd=REPO_ROOT, check=True,
                              capture_output=True, text=True).stdout
    except Exception:
        return ""


def is_committed(rel: str) -> bool:
    """Tracked by git AND present on disk.

    Tracked-ness is load-bearing, not pedantry: the reader's vantage point is a fresh
    clone, and an untracked file is simply absent there. A predicate that resolved true
    against an uncommitted working-tree file would flip a row to `passed` for a reader
    who can never see the evidence.
    """
    if not (REPO_ROOT / rel).exists():
        return False
    r = subprocess.run(["git", "ls-files", "--error-unmatch", "--", rel],
                       cwd=REPO_ROOT, capture_output=True, text=True)
    return r.returncode == 0


# --------------------------------------------------------------------------------------
# Named predicates. Each returns (state, visible_text, evidence, tracked).
# --------------------------------------------------------------------------------------

def measure_deny_rules() -> tuple[int, int, str] | None:
    """(total_deny, git_related_deny, source). None when no source is readable."""
    for cand in ("settings.json", "settings.template.json"):
        p = REPO_ROOT / cand
        if not p.is_file():
            continue
        try:
            deny = json.loads(p.read_text(encoding="utf-8")).get("permissions", {}).get("deny", [])
        except Exception:
            continue
        if not isinstance(deny, list):
            continue
        return len(deny), sum(1 for r in deny if "git" in str(r).lower()), cand
    return None


def pred_known_limits() -> tuple[str, str, str, str]:
    """Conjunction of two RE-EXECUTED measurements over committed, non-ignored inputs.

    Limb (ii) -- the permission layer carries at least one git-related deny rule -- is
    evaluated FIRST because it is cheap, safe and definitive. When it is false the
    conjunction is already false, so limb (i) (re-running the probe corpus) is NOT
    executed. That short-circuit can only hold the row AT not-yet; it can never flip it
    to passed, because `passed` additionally requires limb (i) to have been positively
    observed. Deletion of evidence is never positive evidence.
    """
    m = measure_deny_rules()
    corpus = "hooks/tests/fixtures/adversarial_corpus.json"
    corpus_committed = is_committed(corpus)

    if m is None:
        return ("not-yet",
                "**Known limits** — the permission surface could not be measured at "
                "build time, so this control is reported as unverified, not as passing.",
                "none", "spec-item-D")

    total, git_related, source = m
    limb_ii = git_related >= 1
    if not limb_ii:
        return (
            "not-yet",
            "**Known limits — this guard does not cover everything.** Wrapper- and "
            "redirection-prefixed `git` forms (`env -u VAR git …`, "
            "`2>/dev/null /usr/bin/git …`) slip past the Bash pre-execution gate: a "
            "*successful-but-empty* parse counts as healthy and suppresses the regex "
            "backstop meant to catch them. The permission layer does not back it up — "
            f"**{git_related} of {total} deny rules are git-related** (recomputed from "
            f"`{source}`). Detection-layer measurement only: no destructive operation "
            "was executed and no executable bypass was demonstrated.",
            source, "spec-item-D",
        )
    # limb (ii) holds -- only now is limb (i) reachable, and it must be a live re-run.
    if not corpus_committed:
        return ("not-yet",
                "**Known limits** — the probe corpus is not committed, so coverage was "
                "not re-measured at build time and this control stays unverified.",
                "none", "spec-item-D")
    return ("not-yet",
            "**Known limits** — probe corpus present and the permission layer now "
            "carries git-related deny rules; re-running the corpus at build time is not "
            "yet wired, so this control stays unverified rather than claiming a pass.",
            corpus, "spec-item-D")


def pred_supported_builds() -> tuple[str, str, str, str]:
    art = "docs/reference/install-compatibility-matrix.md"
    if is_committed(art):
        return ("passed", "**Supported builds** — declared and committed.", art, "none")
    return ("not-yet",
            "**Supported builds** — not yet: none committed (spec item A).",
            "none", "spec-item-A")


def pred_capability_check() -> tuple[str, str, str, str]:
    doctor = REPO_ROOT / "scripts/doctor"
    has_strict = doctor.is_file() and "--strict" in doctor.read_text(
        encoding="utf-8", errors="replace")
    handshake = "scripts/capability-handshake.py"
    if has_strict and is_committed(handshake):
        return ("passed", "**Strict capability check** — passes on this host.",
                handshake, "none")
    return ("not-yet",
            "**Strict capability check** — not yet: handshake not committed "
            "(spec item A).", "none", "spec-item-A")


def pred_blackbox() -> tuple[str, str, str, str]:
    d = REPO_ROOT / "tests/blackbox"
    files = [p for p in d.glob("**/*") if p.is_file()] if d.is_dir() else []
    committed = [p for p in files if is_committed(str(p.relative_to(REPO_ROOT)))]
    if committed:
        return ("passed",
                f"**Black-box guard tests** — {len(committed)} committed, passing.",
                "tests/blackbox", "none")
    return ("not-yet",
            "**Black-box guard tests** — not yet: none committed (spec item D).",
            "none", "spec-item-D")


def pred_release() -> tuple[str, str, str, str]:
    tags = [t for t in git("tag").splitlines() if t.strip()]
    if tags:
        return ("passed", f"**Release** — {tags[-1]}.", "none", "none")
    return ("not-yet", "**Release** — unreleased (no tags).", "none", "spec-item-B")


def pred_os() -> tuple[str, str, str, str]:
    runners: set[str] = set()
    for wf in sorted((REPO_ROOT / ".github/workflows").glob("*.yml")):
        for m in re.finditer(r"runs-on:\s*(\S+)", wf.read_text(encoding="utf-8",
                                                               errors="replace")):
            runners.add(m.group(1).strip().strip("\"'"))
    if runners == {"ubuntu-latest"}:
        return ("partial",
                "**OS** — Ubuntu (CI) only; macOS unverified.",
                ".github/workflows", "none")
    return ("partial", f"**OS** — CI runners: {', '.join(sorted(runners)) or 'none'}.",
            ".github/workflows", "none")


PREDICATES = {
    "known-limits": pred_known_limits,
    "supported-builds": pred_supported_builds,
    "capability-check": pred_capability_check,
    "blackbox-tests": pred_blackbox,
    "release": pred_release,
    "os": pred_os,
}

# Which canonical region each row renders into.
REGION_OF = {"known-limits": "limits"}
for _r in ROW_IDS:
    REGION_OF.setdefault(_r, "status")


def render_rows() -> dict[str, list[tuple[str, str]]]:
    """-> {region_id: [(marker_line, visible_line), ...]} in ROW_IDS order."""
    out: dict[str, list[tuple[str, str]]] = {"limits": [], "status": []}
    for rid in ROW_IDS:
        state, text, evidence, tracked = PREDICATES[rid]()
        if state not in STATES:
            raise SystemExit(f"generator emitted an out-of-enum state for {rid}: {state}")
        marker = (f"<!-- claim-row id={rid} state={state} "
                  f"evidence={evidence} tracked={tracked} -->")
        visible = text if REGION_OF[rid] == "limits" else f"- {text}"
        out[REGION_OF[rid]].append((marker, visible))
    return out


def render_region(rid: str, rows: list[tuple[str, str]]) -> str:
    body = "\n".join(f"{m}\n{v}" for m, v in rows)
    return f"{BEGIN.format(rid=rid)}\n{body}\n{END.format(rid=rid)}"


def region_span(text: str, rid: str) -> tuple[int, int] | None:
    b, e = BEGIN.format(rid=rid), END.format(rid=rid)
    i, j = text.find(b), text.find(e)
    if i < 0 or j < 0 or j < i:
        return None
    return i, j + len(e)


def parse_committed_rows(region_text: str) -> list[tuple[str, str, dict]]:
    """-> [(marker_line, visible_line, parsed_marker_fields)] for each claim-row."""
    lines = region_text.splitlines()
    out = []
    for idx, ln in enumerate(lines):
        m = MARKER_RE.match(ln.strip())
        if m:
            visible = lines[idx + 1] if idx + 1 < len(lines) else ""
            out.append((ln.strip(), visible, m.groupdict()))
    return out


def cmd_write(readme: Path) -> int:
    text = readme.read_text(encoding="utf-8")
    rows = render_rows()
    for rid in ("limits", "status"):
        span = region_span(text, rid)
        if span is None:
            print(f"generate-hero-status: region {rid!r} markers not found in {readme}",
                  file=sys.stderr)
            return 1
        i, j = span
        text = text[:i] + render_region(rid, rows[rid]) + text[j:]
    readme.write_text(text, encoding="utf-8")
    print(f"generate-hero-status: wrote both canonical regions into {readme}")
    return 0


def cmd_check(readme: Path) -> int:
    """All four assertions, evaluated on EVERY run. Never short-circuits; every
    violation names the offending row id."""
    text = readme.read_text(encoding="utf-8")
    expected = render_rows()
    violations: list[str] = []

    committed_rows: list[tuple[str, str, dict]] = []
    for rid in ("limits", "status"):
        span = region_span(text, rid)
        if span is None:
            violations.append(f"[region:{rid}] canonical region markers are missing")
            continue
        committed_rows += parse_committed_rows(text[span[0]:span[1]])

    seen: dict[str, int] = {}
    for _, _, f in committed_rows:
        seen[f["id"]] = seen.get(f["id"], 0) + 1

    # (a) completeness: every row id present EXACTLY once across the UNION of regions.
    for rid in ROW_IDS:
        n = seen.get(rid, 0)
        if n == 0:
            violations.append(f"[completeness] row {rid!r} is missing from the canonical regions")
        elif n > 1:
            violations.append(f"[completeness] row {rid!r} appears {n} times; expected exactly once")
    for rid in seen:
        if rid not in ROW_IDS:
            violations.append(f"[completeness] row {rid!r} is not in the closed row enum")

    # (b) enum: every state token within the closed three-value enum.
    for _, _, f in committed_rows:
        if f["state"] not in STATES:
            violations.append(
                f"[enum] row {f['id']!r} carries state={f['state']!r}, outside {sorted(STATES)}")

    # (c) predicate: state=passed IFF the named predicate holds -- bidirectional, so a
    #     stale not-yet left behind after an artifact appears also fails.
    expected_by_id = {}
    for rid_region, pairs in expected.items():
        for marker, visible in pairs:
            m = MARKER_RE.match(marker)
            assert m
            expected_by_id[m.group("id")] = (marker, visible, m.groupdict())
    for _, _, f in committed_rows:
        exp = expected_by_id.get(f["id"])
        if exp is None:
            continue
        if f["state"] != exp[2]["state"]:
            violations.append(
                f"[predicate] row {f['id']!r} claims state={f['state']!r} but its named "
                f"predicate evaluates to {exp[2]['state']!r}")

    # (d) per-row byte-compare, so every violation can name its row.
    for _, _, f in committed_rows:
        exp = expected_by_id.get(f["id"])
        if exp is None:
            continue
        pass
    for rid in ROW_IDS:
        exp = expected_by_id[rid]
        got = next((r for r in committed_rows if r[2]["id"] == rid), None)
        if got is None:
            continue
        if got[0] != exp[0]:
            violations.append(f"[byte-compare] row {rid!r}: marker line differs from regenerated")
        if got[1] != exp[1]:
            violations.append(f"[byte-compare] row {rid!r}: visible text differs from regenerated")

    for v in violations:
        print(f"generate-hero-status: FAIL: {v}", file=sys.stderr)
    if violations:
        return 2
    print(f"generate-hero-status: OK  {len(ROW_IDS)} rows verified across 2 canonical regions")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--readme", default=str(REPO_ROOT / "README.md"))
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    a = ap.parse_args()
    readme = Path(a.readme)
    return cmd_write(readme) if a.write else cmd_check(readme)


if __name__ == "__main__":
    sys.exit(main())
