#!/usr/bin/env python3
"""Write-side ledger for hook-authored side-effect files (backlog #122, M1/M2).

hooks/doc_sync/main.py calls record_landed_files() right after
process_parent_dirs() regenerates a directory's README.md/INDEX.md as a
PostToolUse side effect of a dev agent's own Write/Edit/NotebookEdit call.
Those regenerated files never go through Edit/Write themselves, so they can
never enter a dev-report's own owned_edits ledger (agents/dev.md's
contract) -- this module gives them a separate, honestly-labeled
declaration path that scripts/aggregate-dev-report.py merges into the
existing files_landed_whole exemption channel (backlog #121) for
single-lane (N==1) dev cycles.

Fail-open throughout, mirroring hooks/posttool-codex-skill-ledger.py: never
raise, never block the PostToolUse hook chain. A dev-registry resolution
failure, a git subprocess failure, or a write failure all result in a
silent no-op for that record.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from .regions import RegenStatus

HONEST_REASON = "PostToolUse doc-sync regeneration side effect; not reviewed by dev"


def _now_iso_z() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _diff_sha256(rel_path: str, project_dir: Path) -> str | None:
    """sha256 of `git diff HEAD -- <rel_path>` output, or None on any failure."""
    try:
        proc = subprocess.run(
            ["git", "diff", "HEAD", "--", rel_path],
            cwd=str(project_dir),
            capture_output=True,
            check=False,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if proc.returncode != 0:
        return None
    return hashlib.sha256(proc.stdout).hexdigest()


def _write_entry(ledger_dir: Path, rel_path: str, entry: dict) -> None:
    """Atomically write one entry, content-addressed by path.

    Content-addressing by the regenerated path (not by agent_id, unlike the
    codex-ledger precedent) means re-regeneration of the SAME path within
    one session overwrites its own entry cleanly, while a DIFFERENT path
    regenerated by the same agent_id gets its own file -- no cross-path
    collision, and a torn write to one path's file can never corrupt
    another path's entry.
    """
    ledger_dir.mkdir(parents=True, exist_ok=True)
    name = hashlib.sha256(rel_path.encode("utf-8")).hexdigest() + ".json"
    target = ledger_dir / name
    descriptor, tmp_name = tempfile.mkstemp(prefix=f".{name}.", suffix=".tmp", dir=ledger_dir)
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            json.dump(entry, handle, indent=2, ensure_ascii=False)
            handle.write("\n")
        os.replace(tmp_path, target)
    except OSError:
        tmp_path.unlink(missing_ok=True)


def record_landed_files(results: list, payload: dict, project_dir: Path) -> None:
    """Append a ledger entry for every real (WRITTEN) regeneration in `results`.

    `results` is the list process_parent_dirs() populates (README/INDEX
    RegenRecords for the edited file's parent, and its matching global
    directory). `payload` is the PostToolUse stdin JSON; only `agent_id` is
    read from it here.

    Fail-open: any resolution, computation, or write failure silently
    no-ops (for one record or all of them); this function never raises into
    its caller, and never writes a ledger entry for a non-`dev`-role agent
    or one with no `dev_session_id` (doc_sync fires on every PostToolUse
    Write/Edit/NotebookEdit across the whole harness, not just dev cycles).

    hooks/lib/agent_resolver.py is imported lazily, inside this function's
    own try block, rather than at module scope: it is a sibling of doc_sync/'s
    own parent directory (hooks/), not of doc_sync/ itself, so some
    deployment/test shapes copy the doc_sync/ package tree without its
    hooks/lib/ sibling (e.g. hooks/tests/test_doc_sync_index_notices.py's
    own synthetic-HOME fixture) -- a module-level import there would raise
    ModuleNotFoundError at doc_sync.main import time and crash the entire
    PostToolUse hook chain, which is exactly the failure mode this ledger
    must never cause.
    """
    try:
        if not results:
            return
        agent_id = payload.get("agent_id") if isinstance(payload, dict) else None
        if not agent_id or not isinstance(agent_id, str):
            return
        sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
        from lib.agent_resolver import resolve_dev_registry_entry
        entry_meta = resolve_dev_registry_entry(agent_id, str(project_dir))
        if entry_meta is None or entry_meta.get("agent_type") != "dev":
            return
        dev_session_id = entry_meta.get("dev_session_id")
        if not dev_session_id or not isinstance(dev_session_id, str):
            return
        ledger_dir = Path(project_dir) / ".claude" / "dev-registry" / dev_session_id / "hook-landed-files"
        ts = _now_iso_z()
        for record in results:
            if getattr(record, "status", None) is not RegenStatus.WRITTEN:
                continue
            path = getattr(record, "path", None)
            if path is None:
                continue
            try:
                rel_path = Path(path).relative_to(project_dir).as_posix()
            except ValueError:
                continue
            diff_sha256 = _diff_sha256(rel_path, Path(project_dir))
            if diff_sha256 is None:
                continue
            entry = {
                "path": rel_path,
                "diff_sha256": diff_sha256,
                "reason": HONEST_REASON,
                "source_agent_id": agent_id,
                "ts": ts,
            }
            _write_entry(ledger_dir, rel_path, entry)
    except Exception:
        pass
