#!/usr/bin/env python3
"""Regenerate INDEX.md for a directory."""

import re
from datetime import datetime, timezone
from pathlib import Path
from .regions import (
    INDEX_MARKER_ID, RegenStatus, RegionShape, classify_region, marker_close,
    marker_line_numbers, marker_open,
)
from .tree import build_tree

# Dual-mode import: relative in production, package-context fallback when this
# module is loaded standalone via importlib spec_from_file_location (mirrors the
# regen_readme/tree.py pattern so the git-tracked filter resolves either way).
try:
    from .config import tracked_names, tracked_relpaths, is_github_reserved_subtree
except ImportError:
    import importlib as _importlib
    import os as _os
    import sys as _sys
    _pkg_root = _os.path.dirname(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
    if _pkg_root not in _sys.path:
        _sys.path.insert(0, _pkg_root)
    _cfg = _importlib.import_module("hooks.doc_sync.config")
    tracked_names = _cfg.tracked_names  # type: ignore[no-redef]
    tracked_relpaths = _cfg.tracked_relpaths  # type: ignore[no-redef]
    is_github_reserved_subtree = _cfg.is_github_reserved_subtree  # type: ignore[no-redef]


def _detect_convention(dir_path: Path) -> str:
    """Detect naming convention from existing files."""
    files = list(dir_path.iterdir())
    if not files:
        return 'kebab'
    lower_count = sum(1 for f in files if f.name.islower())
    kebab_count = sum(1 for f in files if '-' in f.name)
    if kebab_count > len(files) // 2:
        return 'kebab'
    if lower_count == len(files):
        return 'lower'
    return 'kebab'


def _build_stats(dir_path: Path) -> dict:
    published = tracked_names(dir_path)
    total = 0
    dirs = 0
    for item in dir_path.iterdir():
        if item.name in ('INDEX.md', 'README.md', '__init__.py', '.DS_Store'):
            continue
        if item.name.startswith('.'):
            continue
        # AC-WS5-1: when git is consulted, list only published (tracked) entries.
        if published is not None and item.name not in published:
            continue
        total += 1
        if item.is_dir():
            dirs += 1
    return {'total': total, 'dirs': dirs}


# A build_tree line is "<indent><connector> <body>", where <indent> is N
# repetitions of a 4-char unit ("│   " or "    "), <connector> is "├── "/"└── ",
# and <body> is either "`name` - desc" (a file) or "name/" (a directory). Parsing
# the indent gives the entry's depth; a name stack reconstructs each entry's full
# relative path so it can be checked against the git-tracked relpath set — pruning
# nested untracked/gitignored entries WITHOUT editing tree.py (out of WS5 scope).
_TREE_LINE_RE = re.compile(r'^((?:(?:│   )|(?:    ))*)([├└]── )(.*)$')


def _parse_tree_entry(line: str):
    """Return (depth, name, is_dir) for a build_tree line, or None if unparseable."""
    m = _TREE_LINE_RE.match(line)
    if not m:
        return None
    depth = len(m.group(1)) // 4
    body = m.group(3)
    if body.endswith('/'):
        return depth, body[:-1], True
    fm = re.match(r'^`([^`]+)`', body)
    if fm:
        return depth, fm.group(1), False
    return None


def _filter_tree_published(tree: list[str], dir_path: Path) -> list[str]:
    """Drop tree lines (at any depth) for entries that are not git-published, so
    the INDEX tree lists only tracked files (AC-WS5-1). A directory is kept iff it
    contains at least one tracked file. Degrades to a no-op when git was not
    consulted (tracked_relpaths -> None)."""
    relpaths = tracked_relpaths(dir_path)
    if relpaths is None:
        return tree
    tracked_dirs = {rp.rsplit('/', 1)[0] for rp in relpaths if '/' in rp}
    kept: list[str] = []
    stack: list[str] = []      # name stack: stack[d] is the ancestor name at depth d
    keep_at: list[bool] = []   # keep_at[d] mirrors whether that ancestor was kept
    for line in tree:
        parsed = _parse_tree_entry(line)
        if parsed is None:
            kept.append(line)
            continue
        depth, name, is_dir = parsed
        del stack[depth:]
        del keep_at[depth:]
        rel = '/'.join(stack + [name])
        if is_dir:
            published = rel in tracked_dirs or any(
                rp == rel or rp.startswith(rel + '/') for rp in relpaths)
        else:
            published = rel in relpaths
        parent_kept = all(keep_at) if keep_at else True
        stack.append(name)
        keep_at.append(published)
        if parent_kept and published:
            kept.append(line)
    return kept


AUTO_START = marker_open(INDEX_MARKER_ID)
AUTO_END = marker_close(INDEX_MARKER_ID)
_FOOTER = '*Auto-generated by doc-sync hook.*'


def _index_needs_update(index_path: Path) -> bool:
    """True only when the INDEX is absent OR its AUTO region is well-formed. Any other existing
    INDEX is left ENTIRELY untouched — this is the regen_readme pattern and is what makes
    annotation-wiping structurally impossible (no unmanaged file is ever rewritten). regen_index
    classifies once itself; this predicate is the same decision for callers that only ask."""
    if not index_path.exists():
        return True
    return classify_region(index_path.read_text(), INDEX_MARKER_ID).shape is RegionShape.WELL_FORMED


def _extract_preserved(old: str, dir_name: str) -> str:
    """Hand-written prose from a MARKED INDEX.md: everything outside the generated region.
    The generated region is the classifier's opening..closing marker lines, so fenced example
    markers in the hand text are never mistaken for it. Strips: the leading title line, that
    region, and the trailing `---`+footer pair at the very end. Human `---`, `**Convention**:`,
    or `## Tree` prose OUTSIDE the region is preserved verbatim. Idempotent. Lines are split on
    newline only: a form feed or U+2028 inside hand text is not a line break."""
    lines = old.split('\n')
    n = len(lines)
    remove = [False] * n
    title = f'# {dir_name}'
    first = 0
    while first < n and not lines[first].strip():
        first += 1
    if first < n and lines[first].rstrip() == title:
        remove[first] = True
    region = classify_region(old, INDEX_MARKER_ID)
    if region.shape is RegionShape.WELL_FORMED:
        for idx in range(region.open_line - 1, region.close_line):
            remove[idx] = True
    last = n - 1
    while last >= 0 and not lines[last].strip():
        last -= 1
    if last >= 0 and lines[last].strip() == _FOOTER:
        p = last - 1
        while p >= 0 and not lines[p].strip():
            p -= 1
        if p >= 0 and lines[p].strip() == '---':
            remove[last] = True
            remove[p] = True
    preserved = [lines[idx] for idx in range(n) if not remove[idx]]
    while preserved and not preserved[0].strip():
        preserved.pop(0)
    while preserved and not preserved[-1].strip():
        preserved.pop()
    return '\n'.join(preserved)


def _build_index_block(dir_path: Path, convention: str) -> list[str]:
    """The generated lines between the markers."""
    tree = _filter_tree_published(build_tree(dir_path, max_depth=3), dir_path)
    ts = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    lines = [
        f'*Last updated: {ts}*',
        f'**Total entries**: {len(tree)}',
        f'**Convention**: {convention}',
        '',
        '## Tree',
        '```',
        f'{dir_path.name}/',
    ]
    lines.extend(tree)
    lines.append('```')
    return lines


def _compose_index(dir_path: Path, block: list[str], preserved: str = '') -> str:
    lines = [f'# {dir_path.name}', '', AUTO_START, *block, AUTO_END]
    if preserved.strip():
        lines.extend(['', preserved])
    lines.extend(['', f'---\n{_FOOTER}'])
    return '\n'.join(lines)


def _build_index_content(dir_path: Path, convention: str, preserved: str = '') -> str:
    return _compose_index(dir_path, _build_index_block(dir_path, convention), preserved)


def regen_index(dir_path: Path, project_dir: Path | None = None) -> RegenStatus:
    """Regenerate INDEX.md, preserving hand-written annotations, and report what happened.

    Only a file that is absent or carries a well-formed AUTO region is managed; every other
    existing INDEX is left untouched (no bytes, no mtime) and its status returned, mirroring
    regen_readme so annotation-wiping is structurally impossible. Content that would put
    marker text of its own into the file (a multi-line description in the tree) is refused
    the same way: a file the classifier rejects on the next run must never be produced here.

    project_dir (the repository root) anchors the GitHub-reserved-subtree check to
    the repo, making it CWD-independent; see config.is_github_reserved_subtree."""
    # Never generate an INDEX under the GitHub-reserved subtree: a stub there is
    # repo-noise (nested) or a landing-page hijack risk. Skip when the folder IS
    # .github or lies beneath it (tested relative to project_dir), robust to
    # non-canonical '..' inputs.
    if is_github_reserved_subtree(dir_path, project_dir):
        return RegenStatus.SKIPPED_GITHUB_RESERVED
    index_path = dir_path / 'INDEX.md'
    old = None
    if index_path.exists():
        old = index_path.read_text()
        skip = classify_region(old, INDEX_MARKER_ID).status
        if skip is not None:
            return skip
    preserved = _extract_preserved(old, dir_path.name) if old is not None else ''
    block = _build_index_block(dir_path, _detect_convention(dir_path))
    if marker_line_numbers('\n'.join(block)):
        return RegenStatus.SKIPPED_MALFORMED_MARKERS
    content = _compose_index(dir_path, block, preserved)
    if classify_region(content, INDEX_MARKER_ID).shape is not RegionShape.WELL_FORMED:
        return RegenStatus.SKIPPED_MALFORMED_MARKERS
    index_path.write_text(content)
    return RegenStatus.WRITTEN
