#!/usr/bin/env python3
"""Subprocess tests for scripts/regen-index-dirs.py.

Backlog #85: the script printed `regenerated: <INDEX>` for every directory, including the ones
regen_index() left untouched, so a run that changed nothing looked like a resync. It now
reports the status regen_index() returns: `regenerated:` only for a write, `skipped (<STATUS>):`
otherwise, and only an INDEX with no marker at all that looks generated gets markers inserted.

Isolation: the script locates its repository root from its own path, so each case runs a COPY
of the script and of the doc_sync package inside a synthetic repository root under tmp_path.
The GitHub-reserved subtree is then that root's .github, and nothing touches the real tree.
HOME and TMPDIR are redirected and the doc-sync environment variables are scrubbed.
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / 'scripts' / 'regen-index-dirs.py'
DOC_SYNC_PACKAGE = REPO_ROOT / 'hooks' / 'doc_sync'
SCRUBBED_ENV = ('CLAUDE_PROJECT_DIR', 'CLAUDE_DOC_SYNC_ROOTS', 'CLAUDE_DOC_SYNC_STATE_ROOT')
EARLIER_NS = 1_000_000_000 * 10**9

IO = '<!-- AUTO:index-stats -->'
IC = '<!-- /AUTO:index-stats -->'
GENERATED = (
    '# folder\n\n*Last updated: 2001-01-01T00:00:00Z*\n**Total entries**: 1\n**Convention**: kebab\n\n'
    '## Tree\n```\nfolder/\n└── `alpha.py` - Alpha helper.\n```\n\nhand annotation\n\n'
    '---\n*Auto-generated by doc-sync hook.*\n')


class Sandbox:
    """A synthetic repository root holding a copy of the script and of the doc_sync package."""

    def __init__(self, root):
        self.root = Path(root)
        self.home = self.root / 'home'
        self.tmp_root = self.root / 'tmp'
        self.repo = self.root / 'repo'
        for directory in (self.home, self.tmp_root, self.repo / 'scripts', self.repo / 'hooks'):
            directory.mkdir(parents=True)
        shutil.copy(SCRIPT, self.repo / 'scripts' / 'regen-index-dirs.py')
        shutil.copytree(DOC_SYNC_PACKAGE, self.repo / 'hooks' / 'doc_sync',
                        ignore=shutil.ignore_patterns('__pycache__', 'README.md', 'INDEX.md'))

    def directory(self, name='folder'):
        directory = self.repo / name
        directory.mkdir(parents=True, exist_ok=True)
        (directory / 'alpha.py').write_text('"""Alpha helper."""\n')
        return directory

    def run(self, *arguments):
        environment = {key: value for key, value in os.environ.items() if key not in SCRUBBED_ENV}
        environment.update(HOME=str(self.home), TMPDIR=str(self.tmp_root), PYTHONDONTWRITEBYTECODE='1')
        return subprocess.run(
            [sys.executable, str(self.repo / 'scripts' / 'regen-index-dirs.py'), *[str(a) for a in arguments]],
            capture_output=True, text=True, env=environment, cwd=str(self.home), timeout=120)


def pinned(path):
    os.utime(path, ns=(EARLIER_NS, EARLIER_NS))
    return path.read_bytes(), path.stat().st_mtime_ns


def test_script_case_sc_unmarkable_skipped(tmp_path):
    """An INDEX with no recognisable generated block is skipped, reported as such and left alone."""
    sandbox = Sandbox(tmp_path)
    directory = sandbox.directory()
    index = directory / 'INDEX.md'
    index.write_text('# folder\n\nhand written notes only\n')
    before = pinned(index)

    completed = sandbox.run(directory)

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout == f'skipped (SKIPPED_NO_OPENING_MARKER): {index}\n'
    assert 'regenerated:' not in completed.stdout
    assert (index.read_bytes(), index.stat().st_mtime_ns) == before


def test_script_case_sc_generator_shape_marker_inserted_regenerated(tmp_path):
    """A markerless INDEX shaped like generator output gets markers around its block and is regenerated."""
    sandbox = Sandbox(tmp_path)
    directory = sandbox.directory()
    index = directory / 'INDEX.md'
    index.write_text(GENERATED)

    completed = sandbox.run(directory)

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout == f'regenerated: {index}\n'
    text = index.read_text()
    assert text.count(IO) == 1 and text.count(IC) == 1
    assert text.count('*Last updated:') == 1 and 'hand annotation' in text and '2001-01-01' not in text


def test_script_case_sc_open_only_skipped_no_closing(tmp_path):
    """An INDEX with an opening marker only is skipped (it used to be rewritten with a duplicate block)."""
    sandbox = Sandbox(tmp_path)
    directory = sandbox.directory()
    index = directory / 'INDEX.md'
    index.write_text(f'# folder\n\n{IO}\n*Last updated: 2001-01-01T00:00:00Z*\n')
    before = pinned(index)

    completed = sandbox.run(directory)

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout == f'skipped (SKIPPED_NO_CLOSING_MARKER): {index}\n'
    assert (index.read_bytes(), index.stat().st_mtime_ns) == before


def test_script_case_sc_close_only_skipped_no_opening(tmp_path):
    """An INDEX with a closing marker only is skipped as having no opening marker."""
    sandbox = Sandbox(tmp_path)
    directory = sandbox.directory()
    index = directory / 'INDEX.md'
    index.write_text(f'# folder\n\n{IC}\n')
    before = pinned(index)

    completed = sandbox.run(directory)

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout == f'skipped (SKIPPED_NO_OPENING_MARKER): {index}\n'
    assert (index.read_bytes(), index.stat().st_mtime_ns) == before


def test_script_case_sc_wellformed_regenerated(tmp_path):
    """A well-formed INDEX is regenerated and reported as such."""
    sandbox = Sandbox(tmp_path)
    directory = sandbox.directory()
    index = directory / 'INDEX.md'
    index.write_text(f'# folder\n\n{IO}\nstale\n{IC}\n')

    completed = sandbox.run(directory)

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout == f'regenerated: {index}\n'
    assert 'stale' not in index.read_text() and 'alpha.py' in index.read_text()


def test_script_case_sc_github_unchanged(tmp_path):
    """The GitHub-reserved subtree keeps its skip line and its INDEX byte-unchanged."""
    sandbox = Sandbox(tmp_path)
    directory = sandbox.directory('.github')
    index = directory / 'INDEX.md'
    index.write_text(f'# .github\n\n{IO}\nstale\n{IC}\n')
    before = pinned(index)

    completed = sandbox.run(directory)

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout == f'skipped (GitHub-reserved subtree): {index}\n'
    assert (index.read_bytes(), index.stat().st_mtime_ns) == before


def test_script_case_sc_nondir_exit_one(tmp_path):
    """An argument that is not a directory is still a usage error: exit 1, message on stderr."""
    sandbox = Sandbox(tmp_path)
    plain_file = sandbox.repo / 'plain.txt'
    plain_file.write_text('x\n')

    completed = sandbox.run(plain_file)

    assert completed.returncode == 1
    assert 'not a directory' in completed.stderr
    assert completed.stdout == ''
    assert sandbox.run().returncode == 1


def test_script_case_sc_exit_zero_on_skip(tmp_path):
    """Skips never fail the run: several directories, mixed outcomes, exit 0, one line each."""
    sandbox = Sandbox(tmp_path)
    skipped = sandbox.directory('skipped')
    (skipped / 'INDEX.md').write_text('# skipped\n\nhand written\n')
    managed = sandbox.directory('managed')
    (managed / 'INDEX.md').write_text(f'# managed\n\n{IO}\nstale\n{IC}\n')

    completed = sandbox.run(skipped, managed)

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout.splitlines() == [
        f'skipped (SKIPPED_NO_OPENING_MARKER): {skipped / "INDEX.md"}', f'regenerated: {managed / "INDEX.md"}']


def test_script_case_sc_prose_marker_mention_not_a_marker(tmp_path):
    """Marker text inside prose or a fenced example is not a marker: no opt-in, no takeover."""
    sandbox = Sandbox(tmp_path)
    prose = sandbox.directory('prose')
    (prose / 'INDEX.md').write_text(f'# prose\n\nUse `{IO}` and `{IC}` to opt in.\n')
    fenced = sandbox.directory('fenced')
    (fenced / 'INDEX.md').write_text(f'# fenced\n\n```\n{IO}\nexample\n{IC}\n```\n')
    generated = sandbox.directory('generated')
    (generated / 'INDEX.md').write_text(GENERATED.replace('hand annotation', f'mention of {IO} in prose'))
    untouched = {name: (directory / 'INDEX.md').read_bytes() for name, directory in
                 (('prose', prose), ('fenced', fenced))}

    completed = sandbox.run(prose, fenced, generated)

    assert completed.returncode == 0, completed.stderr
    assert completed.stdout.splitlines() == [
        f'skipped (SKIPPED_NO_OPENING_MARKER): {prose / "INDEX.md"}',
        f'skipped (SKIPPED_NO_OPENING_MARKER): {fenced / "INDEX.md"}',
        f'regenerated: {generated / "INDEX.md"}']
    assert (prose / 'INDEX.md').read_bytes() == untouched['prose']
    assert (fenced / 'INDEX.md').read_bytes() == untouched['fenced']
    text = (generated / 'INDEX.md').read_text()
    assert text.count(f'\n{IO}\n') == 1 and f'mention of {IO} in prose' in text and text.count('*Last updated:') == 1


def test_script_case_sc_bytes_unchanged_on_skip(tmp_path):
    """Every skip shape leaves the INDEX bytes and mtime alone, malformed shapes included."""
    sandbox = Sandbox(tmp_path)
    shapes = {
        'duplicate': f'{IO}\nx\n{IO}\ny\n{IC}\n',
        'reversed': f'{IC}\nmiddle\n{IO}\nstale\n',
        'near_miss': '# near\n<!--AUTO:index-stats-->\nstale\n',
        'inline_pair': f'# inline\n{IO} {IC}\n',
        'zero_bytes': '',
    }
    expected = {'duplicate': 'SKIPPED_MALFORMED_MARKERS', 'reversed': 'SKIPPED_NO_CLOSING_MARKER',
                'near_miss': 'SKIPPED_MALFORMED_MARKERS', 'inline_pair': 'SKIPPED_MALFORMED_MARKERS',
                'zero_bytes': 'SKIPPED_NO_OPENING_MARKER'}
    for name, text in shapes.items():
        directory = sandbox.directory(name)
        index = directory / 'INDEX.md'
        index.write_text(text)
        before = pinned(index)

        completed = sandbox.run(directory)

        assert completed.returncode == 0, (name, completed.stderr)
        assert completed.stdout == f'skipped ({expected[name]}): {index}\n', name
        assert (index.read_bytes(), index.stat().st_mtime_ns) == before, name
